// Central site/business info. All values verbatim from eurotsdubai.com.
export const site = {
  name: "Eurots Dubai",
  legalName: "EUROTS DUBAI SERVICES LLC",
  tagline: "The largest & most trusted independent maintenance company in Dubai",
  established: 2008,
  phoneDisplay: "055 669 5572",
  phoneHref: "tel:0556695572",
  freephoneDisplay: "800 FIX (800 349)",
  freephoneHref: "tel:800349",
  whatsappDisplay: "+971 55 669 5572",
  whatsappHref: "https://wa.me/971556695572",
  whatsappNumber: "971556695572",
  email: "info@eurotsdubai.com",
  emailHref: "mailto:info@eurotsdubai.com",
  address: {
    line1: "Phase 1 – Plot 194",
    line2: "Dubai Investments Park – Dubai",
  },
  hours: [
    { day: "Customer call centre", time: "Open 24 hours" },
    { day: "Monday", time: "8:00 am – 6:00 pm" },
    { day: "Tuesday", time: "8:00 am – 6:00 pm" },
    { day: "Wednesday", time: "8:00 am – 5:00 pm" },
    { day: "Thursday", time: "8:00 am – 5:00 pm" },
    { day: "Friday", time: "8:00 am – 5:00 pm" },
    { day: "Saturday", time: "8:00 am – 5:00 pm" },
    { day: "Sunday", time: "CLOSED" },
  ],
  stats: {
    jobs: 420000,
    customers: 47000,
    partsWarranty: 12,
    serviceWarranty: 3,
    reviewsRating: 4.7,
    reviewsCount: 2341,
  },
  serviceOptions: [
    "Annual Maintenance Contract",
    "AC Servicing",
    "Duct Cleaning",
    "Coil Cleaning",
    "Plumbing",
    "Electrical",
    "Handyman",
    "Carpentry",
    "Drainage",
    "Painting",
    "Swimming Pools & Waterproofing",
    "Water Tank Cleaning",
    "Other",
  ],
  socials: {
    instagram: "https://www.instagram.com/",
    facebook: "https://www.facebook.com/",
    linkedin: "https://www.linkedin.com/",
  },
};